function [BW,maskedImage] = cut2(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 16-Jun-2022
%----------------------------------------------------


% Threshold image - manual threshold
BW = X > 66;

% Close mask with disk
radius = 100;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Dilate mask with disk
radius = 11;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imdilate(BW, se);

% Active contour
iterations = 30;
BW = activecontour(X, BW, iterations, 'Chan-Vese');

% Dilate mask with disk
radius = 6;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imdilate(BW, se);

% Close mask with disk
radius = 68;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

