function [BW,maskedImage] = segmentImageLight(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 13-Jun-2022
%----------------------------------------------------


% Adjust data to span data range.
X = imadjust(X);

% Threshold image - manual threshold
BW = X > 83;

% Erode mask with disk
radius = 23;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imerode(BW, se);

% Active contour
iterations = 100;
BW = activecontour(X, BW, iterations, 'Chan-Vese');

% Active contour
iterations = 90;
BW = activecontour(X, BW, iterations, 'Chan-Vese');

% Erode mask with diamond
radius = 16;
se = strel('diamond', radius);
BW = imerode(BW, se);

% Active contour
iterations = 100;
BW = activecontour(X, BW, iterations, 'Chan-Vese');

% Close mask with disk
radius = 30;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Close mask with disk
radius = 41;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Active contour
iterations = 8;
BW = activecontour(X, BW, iterations, 'Chan-Vese');

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

