function [BW,maskedImage] = segmentImage(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 13-Jun-2022
%----------------------------------------------------


% Adjust data to span data range.
X = imadjust(X);

% Threshold image - manual threshold
BW = X > 183;

% Dilate mask with disk
radius = 10;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imdilate(BW, se);

% Active contour
iterations = 106;
BW = activecontour(X, BW, iterations, 'Chan-Vese');

% Dilate mask with disk
radius = 10;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imdilate(BW, se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

